### ISSUE TITLE
Emulation Menu in M64py 0.2.5 on windows

### ISSUE THREAD

**Issue by ZachBacon** [mupen64plus/mupen64plus-ui-python#158]
Seems in m64py's current release the ability to save states or even stop or reset the emulator is unselectable at the moment, I have yet to test on other platforms like MacOS or linux for the moment. But will do so relatively soon.
![m64py](https://user-images.githubusercontent.com/8948676/79058461-833e4680-7c3c-11ea-9ee1-7b0dcff537f4.png)

**Comment by gen2brain** [comment]
That is because of a hacky way to change actions state after the ROM is opened https://github.com/mupen64plus/mupen64plus-ui-python/blob/master/src/m64py/frontend/mainwindow.py#L312 . There are events for rom_opened/close but not for rom_started or something like that. 

Happens to me usually when I am on a slow computer or when testing in VM.

**Comment by ZachBacon** [comment]
I don't have a slow computer, nor am I using a VM. I'm not overly great at python, but I suppose I could attempt to dig in the code and see if I can resolve it and submit a PR

**Comment by Zixiken** [comment]
Ah, I think you're on to something here. In mint package management are versions 2.5.0 of core and plugins, and it finishes initializing before that 2 second timer. But when I switch to the latest versions that I've built, initialization hasn't finished when the timer expires, so core_state_query(M64CORE_EMU_STATE) returns M64EMU_STOPPED.
