### ISSUE TITLE
[Errno 2] No such file or directory: 'lrelease'

### ISSUE THREAD

**Issue by LonelyMusicDisc** [mupen64plus/mupen64plus-ui-python#173]
python3 setup.py build
running build
running build_qt
error: [Errno 2] No such file or directory: 'lrelease'

**Comment by CDGDVD** [comment]
I'm using Linux mint (cinnamon) btw.

**Comment by evereux** [comment]
Confirmed.

The problem seems to relate to [this commit](https://github.com/mupen64plus/mupen64plus-ui-python/commit/97d694bfec8bd1d3bd4571f0294fed73eba846fe#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7).

maybe @gen2brain can help here?

I rolled back the 2.5 release and mananged to build fine.

**Comment by gen2brain** [comment]
You are just missing some package that contains `lrelease` util. Not sure which one, and what distro you are on, for me, I just install PyQt5 and everything is there. Some distros split that into many different packages.

**Comment by Unounited** [comment]
`sudo apt install qt5-default libpcap-dev libncurses5-dev libprocps-dev libxtst-dev libxcb-util0-dev qttools5-dev-tools libdtkwidget-dev libdtkwm-dev pkg-config` worked for me

**Comment by asiplas** [comment]
For what it's worth,  Fedora names the binary `lrelease-qt5` so a symlink or adjustment to [setup.py](https://github.com/mupen64plus/mupen64plus-ui-python/blob/0a08a32481f3de8bb91d5f3e2c653ed9114e5347/setup.py#L71) is needed.

**Comment by LonelyMusicDisc** [comment]
this issue will be closed since I'm not using mupen64plus as of now.
please reopen if you have the same issue/it isn't fixed
